name: mkosi

on:
  workflow_dispatch:

jobs:
  mkosi:
    runs-on: ubuntu-latest
    steps:
    - name: setup-mkosi
      uses: systemd/mkosi@main
    - run: |
        sudo apt -y update
        mkosi dependencies -- --profile runtime | xargs -d '\n' sudo apt -y install        
    - run: |
        set -x
        mkdir -p mkosi.extra/etc/apt/sources.list.d/ mkosi.extra/root/
        cat << EOF > mkosi.extra/etc/apt/sources.list.d/ubuntu.sources
        Types: deb
        URIs: http://archive.ubuntu.com/ubuntu/
        Suites: noble noble-updates noble-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: noble-security
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        EOF
        cat << EOF > mkosi.extra/root/.profile
        set -x
        apt -y -o DPkg::Lock::Timeout=-1 update
        poweroff
        EOF
    # - timeout-minutes: 10
    #   run: |
    #     mkosi \
    #       --distribution=ubuntu \
    #       --release=noble \
    #       --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic \
    #       --repositories=universe \
    #       --autologin=yes \
    #       --ephemeral=yes \
    #       --tpm=no \
    #       --force \
    #       vm
    - timeout-minutes: 10
      run: |
        set -x
        mkosi genkey
        mkosi \
          --machine=test0 \
          --distribution=ubuntu \
          --release=noble \
          --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic,openssh-server \
          --repositories=universe \
          --tpm=no \
          --force \
          --console=headless \
          --ssh=always \
          --vsock=no \
          --register=yes \
          build
        mkosi \
          --machine=test0 \
          --distribution=ubuntu \
          --release=noble \
          --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic,openssh-server \
          --repositories=universe \
          --tpm=no \
          --ssh=always \
          --vsock=no \
          --register=yes \
          vm &
        sleep 30
        sudo mkosi \
          --machine=test0 \
          --distribution=ubuntu \
          --release=noble \
          --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic,openssh-server \
          --repositories=universe \
          --tpm=no \
          --console=headless \
          --ssh=always \
          --vsock=no \
          --register=yes \
          ssh
