name: mkosi

on:
  workflow_dispatch:

jobs:
  mkosi:
    runs-on: ubuntu-latest
    steps:
    - name: setup-mkosi
      uses: systemd/mkosi@main
    - run: |
        sudo apt -y update
        mkosi dependencies -- --profile runtime | xargs -d '\n' sudo apt -y install        
    - run: |
        set -x
        mkdir -p mkosi.repart/ mkosi.extra/etc/apt/sources.list.d/
        cat << EOF > mkosi.repart/00-esp.conf
        [Partition]
        Type=esp
        Format=vfat
        CopyFiles=/boot:/
        CopyFiles=/efi:/
        SizeMinBytes=512M
        SizeMaxBytes=512M
        EOF
        cat << EOF > mkosi.repart/10-root.conf
        [Partition]
        Type=root
        Format=ext4
        CopyFiles=/
        SizeMinBytes=8G
        SizeMaxBytes=8G
        EOF
        cat << EOF > mkosi.extra/etc/apt/sources.list.d/ubuntu.sources
        Types: deb
        URIs: http://archive.ubuntu.com/ubuntu/
        Suites: noble noble-updates noble-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: noble-security
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        EOF
    - timeout-minutes: 10
      run: |
        set -x
        mkosi genkey
        mkosi \
          --architecture=arm64 \
          --distribution=ubuntu \
          --release=noble \
          --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic,openssh-server,tree \
          --repositories=universe \
          --ssh=always \
          build
        mkosi \
          --tpm=no \
          --console=headless \
          --runtime-build-sources=yes \
          vm &
        while ! mkosi ssh -- exit ; do sleep 1 ; done
        mkosi ssh -- -o BatchMode=yes bash << EOF
        set -xe
        sudo apt -y update
        uname -a
        df -h
        lsblk
        tree /work/
        touch /work/src/hello
        EOF
        ls
