name: mkosi

on:
  workflow_dispatch:

jobs:
  mkosi:
    runs-on: ubuntu-latest
    steps:
    - name: setup-mkosi
      uses: systemd/mkosi@main
    - run: |
        sudo apt -y update
        mkosi dependencies -- --profile runtime | xargs -d '\n' sudo apt -y install        
    - run: |
        set -x
        mkdir -p mkosi.extra/etc/apt/sources.list.d/ mkosi.extra/root/
        cat << EOF > mkosi.extra/etc/apt/sources.list.d/ubuntu.sources
        Types: deb
        URIs: http://archive.ubuntu.com/ubuntu/
        Suites: noble noble-updates noble-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: noble-security
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        EOF
    - timeout-minutes: 10
      run: |
        set -x
        mkosi genkey
        mkosi \
          --distribution=ubuntu \
          --release=noble \
          --package=systemd-boot,systemd-resolved,ubuntu-minimal,linux-image-generic,openssh-server \
          --repositories=universe \
          --ssh=always \
          --output-size=8G \
          build
        mkosi \
          --tpm=no \
          --console=headless \
          vm &
        while ! mkosi ssh -- exit ; do sleep 1 ; done
        mkosi ssh -- -o BatchMode=yes bash << EOF
        set -xe
        uname -a
        df -h
        EOF
