name: virt-install

on:
  workflow_dispatch:

jobs:
  virt-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: cache
      uses: actions/cache@v5
      with:
        path: ubuntu-24.04.4-desktop-amd64.iso
        key: ubuntu-24.04.4-desktop-amd64
    - if: steps.cache.outputs.cache-hit != 'true'
      run: wget --quiet https://releases.ubuntu.com/24.04.4/ubuntu-24.04.4-desktop-amd64.iso
    - run: |
        set -x
        sudo apt -y update
        sudo apt -y install libvirt-daemon-system virtinst qemu-system
        cat > user-data << 'EOF'
        #cloud-config
        autoinstall:
        version: 1
        identity:
            hostname: ubuntu-server
            password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
            username: ubuntu
        EOF
        sudo mv ubuntu-24.04.4-desktop-amd64.iso /var/
    - timeout-minutes: 10
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        sudo virt-install \
            --noreboot \
            --check disk_size=off \
            --disk size=1000 \
            --osinfo ubuntunoble \
            --cdrom /var/ubuntu-24.04.4-desktop-amd64.iso \
            --extra-args "autoinstall console=ttyS0 systemd.journald.forward_to_console=yes" \
            --location /var/ubuntu-24.04.4-desktop-amd64.iso,kernel=/casper/vmlinuz,initrd=/casper/initrd \
            --cloud-init user-data=user-data \
            --graphics none
